Repository hmcts/rd-judicial-api, pull requests merged in 2020-10, with the labels that each got.

#70 TF 0.12.2 syntax updates and clean-up - Master
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/prod.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-70

#71 TF Upgrade to 13.3 and Azure RM to 2.25+ - Master
  infrastructure/.terraform-version
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-71

#72 Fix : Jar bumps up and owasp update(RDCC-1933)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-72

#76 adding suppressions to fix the build
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-76

#77 refactor: Altered Audit & Exceptions table (RDCC-1924)
  src/main/resources/db/migration/V1_12__alter_audit_exception_table.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-77
