Repository hmcts/rd-judicial-api, pull requests merged in 2020-04, with the labels that each got.

#25 fix: vulnerabilities updates
  build.gradle
  config/owasp/suppressions.xml
  infrastructure/main.tf
Labels: ns:rd, rel:rd-judicial-api-pr-25

#27 fix: asc flag update
  infrastructure/variables.tf
Labels: ns:rd, rel:rd-judicial-api-pr-27

#28 refactor:removed webapp module from main.tf
  infrastructure/main.tf
Labels: ns:rd, rel:rd-judicial-api-pr-28

#29 refactor: Update infra module config
  infrastructure/main.tf
Labels: ns:rd, rel:rd-judicial-api-pr-29

#30 refactor: updated output.tf
  infrastructure/output.tf
Labels: ns:rd, rel:rd-judicial-api-pr-30

#33 config:updated chart version
  charts/rd-judicial-api/Chart.yaml
  charts/rd-judicial-api/requirements.yaml
Labels: ns:rd, rel:rd-judicial-api-pr-33

#32 feat:schema updates for JRD JSR and Auditing(RDCC-1223)
  Jenkinsfile_nightly
  build.gradle
  src/main/resources/db/migration/V1_4__alter_jrd_tables.sql
  src/main/resources/db/migration/V1_5__defult_insert_leaf_tables.sql
  src/main/resources/db/migration/V1_6__excption_table.sql
  src/main/resources/db/migration/V1_7__audit_table.sql
  src/main/resources/db/migration/V1_8__delete_judicialrole_type_insert.sql
Labels: ns:rd, rel:rd-judicial-api-pr-32

#34 refactor: bump up JRD charts
  charts/rd-judicial-api/Chart.yaml
Labels: ns:rd, rel:rd-judicial-api-pr-34

#35 refactor: flyway update
  src/main/resources/db/migration/V1_9__defult_insert_leaf_tables_not_exists.sql
Labels: ns:rd, rel:rd-judicial-api-pr-35

#36 fix: datasource connection settings updated
  src/main/java/uk/gov/hmcts/reform/judicialapi/JudicialApplication.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/DataSourceConfig.java
  src/main/resources/application.yaml
Labels: ns:rd, rel:rd-judicial-api-pr-36
