Repository hmcts/rd-judicial-api, pull requests merged in 2020-12, with the labels that each got.

#83 build: Addressed CVEs CVE-2020-13956 CVE-2020-17527
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-83

#81 Add sync method call
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-81

#82 DTSPO-266 Enable self service read only access
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-82

#84 CVE-2020-8908: Fixing the CVE.
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-84
