Repository hmcts/rd-judicial-api, pull requests merged in 2020-05, with the labels that each got.

#37 fix: Demo aks changes
  Jenkinsfile_CNP
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
Labels: ns:rd, rel:rd-judicial-api-pr-37

#38 refactor: Suppression xml cleanup (RDCC-1336)
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/judicialapi/JudicialApplication.java
Labels: ns:rd, rel:rd-judicial-api-pr-38

#40 RDCC-1440: removing installCharts() from Jenkinsfiles
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
Labels: ns:rd, rel:rd-judicial-api-pr-40
