Repository hmcts/rd-judicial-api, pull requests merged in 2020-09, with the labels that each got.

#62 fix: Nightly build fix
  build.gradle
  src/main/java/uk/gov/hmcts/reform/judicialapi/JudicialApplication.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-62

#63 fix: Terraform version upgrade
  infrastructure/state.tf
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-63

#64 fix: Terraform version fix
  infrastructure/.terraform-version
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-64

#65 fix: Terraform updates
  infrastructure/state.tf
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-65

#66 fix:Terraform version fix
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/terraform.tf
  infrastructure/test_config.tf
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-66

#67 Nightly fix jrd a pi
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-67

#68 Fix quote issue
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-68
