Repository hmcts/rd-judicial-api, pull requests merged in 2021-07, with the labels that each got.

#145 change the sequence in security.sh to fix security scan
  security.sh
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-145

#144 Add auto-update config for PR branches
  .github/workflows/autoupdate.yml
Labels: DO NOT MERGE, ns:rd, prd:rd, rel:rd-judicial-api-pr-144

#146 fix:RDCC-3087 extended the suppression date as the fix is not yet pro…
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-146

#141 refactor: JRD db model changes with new JRD requirements(RDCC-2833)
  src/integrationTest/resources/db/testmigration/V1_10__alter_user_profile_with_guid.sql
  src/integrationTest/resources/db/testmigration/V1_11__audit_job.sql
  src/integrationTest/resources/db/testmigration/V1_11__drop_and_recreate_auth_table.sql
  src/integrationTest/resources/db/testmigration/V1_12__insert_test_data.sql
  src/integrationTest/resources/db/testmigration/V1_15__insert_test_data.sql
  src/integrationTest/resources/db/testmigration/V1_1__init_tables.sql
  src/integrationTest/resources/db/testmigration/V1_3__alter_jrd_tables.sql
  src/integrationTest/resources/db/testmigration/V1_3__insert_judicialrole_type.sql
  src/integrationTest/resources/db/testmigration/V1_4__alter_jrd_tables.sql
  src/integrationTest/resources/db/testmigration/V1_4__defult_insert_leaf_tables.sql
  src/integrationTest/resources/db/testmigration/V1_5__defult_insert_leaf_tables.sql
  src/integrationTest/resources/db/testmigration/V1_5__excption_table.sql
  src/integrationTest/resources/db/testmigration/V1_6__audit_table.sql
  src/integrationTest/resources/db/testmigration/V1_7__alter_user_profile.sql
  src/integrationTest/resources/db/testmigration/V1_8__alter_audit_exception_table.sql
  src/integrationTest/resources/db/testmigration/V1_8__delete_judicialrole_type_insert.sql
  src/integrationTest/resources/db/testmigration/V1_9__alter_judicial_user_profile.sql
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/AppointmentResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/Appointment.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/Authorisation.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/BaseLocationType.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/ContractType.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/RoleType.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/UserProfile.java
  src/main/resources/db/migration/V1_16__alter_jrd_tables.sql
  src/main/resources/db/migration/V1_17__create_mapping_tables.sql
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/TestSupport.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/controller/response/AppointmentResponseTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/domain/AppointmentTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/domain/BaseLocationTypeTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/domain/ContractTypeTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/domain/RoleTypeTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/domain/UserProfileTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-141

#148 fix: flyway issue
  src/main/resources/db/migration/V1_16__create_mapping_tables.sql
  src/main/resources/db/migration/V1_17__alter_jrd_tables.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-148

#147 RDCC-3110: Update the judicial_location_mapping table
  src/integrationTest/resources/db/testmigration/V1_18__alter_judicial_location_mapping_table.sql
  src/main/resources/db/migration/V1_18__alter_judicial_location_mapping_table.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-147

#149 added script for create and insert for new table jrd_lrd_region_mappings
  src/main/resources/db/migration/V1_19__create_jrd_lrd_region_mappings.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-149

#151 RDCC-3141: fixed CVE
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-151

#150 RDCC-3113: JRD - Update the judicial_service_code_mapping table
  src/integrationTest/resources/db/testmigration/V1_19__create_jrd_lrd_region_mappings.sql
  src/integrationTest/resources/db/testmigration/V1_20__alter_judicial_service_code_mapping_table.sql
  src/main/resources/db/migration/V1_20__alter_judicial_service_code_mapping_table.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-150

#153 RDCC-3150 - Update repositories reference to Jitpack
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-153

#154 RDCC-2963: PACT and Functional test to complete for of JRD POST API
  Jenkinsfile_CNP
  build.gradle
  charts/rd-judicial-api/Chart.yaml
  charts/rd-judicial-api/values.preview.template.yaml
  charts/rd-judicial-api/values.yaml
  src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/AuthorizationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/JudicialUsersFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/client/JudicialApiClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/FetchUsersIntegrationTest.java
  src/main/resources/application.yaml
  src/main/resources/db/migrationAks/V2_1__insert_user_profiles.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-154

#155 RDCC-2963_nightly_fix: Add config to fix nightly build failure
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-155
