Repository hmcts/rd-judicial-api, pull requests merged in 2021-09, with the labels that each got.

#167 feat: RDCC-3230 Added flyway script for new row_id column in exception table
  src/main/resources/db/migration/V1_24__alter_dataload_exception_records_add_row_id.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-167

#166 Add fortify implementation
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-166

#170 feat: RDCC-3230 Added flyway script for new row_id column in exception table
  src/main/resources/db/migration/V1_24__alter_dataload_exception_records_add_row_id.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-170

#168 RDCC-3277: Removed hard coded string in the configuration files.
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  bin/run-in-docker.sh
  charts/rd-judicial-api/Chart.yaml
  charts/rd-judicial-api/values.preview.template.yaml
  charts/rd-judicial-api/values.yaml
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/resources/application.yml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-168

#169 feat: RDCC-2920 Auto-complete feature for searching the Judicial Reference Data
  src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/JudicialUsersFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/client/JudicialApiClient.java
  src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/util/CustomSerenityRunner.java
  src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/util/constants/SqlQueryConstant.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/FetchUsersIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/SearchUsersIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/JudicialReferenceDataClient.java
  src/integrationTest/resources/db/testmigration/V1_21__alter_judicial_office_authorisation.sql
  src/integrationTest/resources/db/testmigration/V1_22__alter_judicial_office_appointment.sql
  src/integrationTest/resources/db/testmigration/V1_23__alter_judicial_office_authorisation_appointment_location_mapping_tables.sql
  src/integrationTest/resources/db/testmigration/V1_24__alter_dataload_exception_records_add_row_id.sql
  src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/LaunchDarklyConfiguration.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/JrdUsersController.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/advice/ExceptionMapper.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/request/UserSearchRequest.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/UserSearchResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/Appointment.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/Authorisation.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/BaseLocationType.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/RegionType.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/UserProfile.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/repository/UserProfileRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/FeatureToggleService.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/JudicialUserService.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/FeatureToggleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/util/FeatureConditionEvaluation.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/util/JrdConstant.java
  src/main/resources/application.yaml
  src/main/resources/db/migrationAks/V2_2__insert_appt_auth_user_profile.sql
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/controller/JrdUsersControllerTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/controller/advice/ExceptionMapperTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/FeatureToggleServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/util/FeatureConditionEvaluationTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-169
