Repository hmcts/rd-judicial-api, pull requests merged in 2021-04, with the labels that each got.

#95 refactor: added sidam column and updated length of object id
  src/main/resources/db/migration/V1_14__alter_user_profile_with_guid.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-95

#96 fix: refactor fly-way with object_id reverting varchar(64)
  src/main/resources/db/migration/V1_14__alter_user_profile_with_guid.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-96

#94 Adding dependabot , fix CVE
  .dependabot/config.yml
  .github/renovate.json
  .github/stale.yml
  .gitignore
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-94

#97 fix:RDCC-2746-Helm chart version updated
  charts/rd-judicial-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-97
