Repository hmcts/rd-judicial-api, pull requests merged in 2021-06, with the labels that each got.

#113 RDCC-2837 changed all Compile and testCompile entries to implementation and testImplementation
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-113

#122 refactor: ASB JRD db script(RDCC-2835)
  src/main/resources/db/migration/V1_15__audit_job.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-122

#127 RDCC-2944: Fix nightly build failure (JRD API)
  Jenkinsfile_nightly
  audit.json
  build.gradle
  security.sh
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/FeatureToggleServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/util/FeatureConditionEvaluationTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-127

#129 upgraded springboot version from 2.4.5 to 2.4.6 to fix cvv
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-129

#138 Feat: RDCC-2875/2919; Create and Insert Data into Mapping tables for IAC locations for the Service code BFA1
  src/integrationTest/resources/db/testmigration/V1_16__create_mapping_tables.sql
  src/main/resources/db/migration/V1_16__create_mapping_tables.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-138

#140 added config for serenity report in nightly job
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-140
