Repository hmcts/rd-judicial-api, pull requests merged in 2021-12, with the labels that each got.

#195 feat: RDCC-3760 Returned 200 empty array instead of 404 when no data found for search string
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/JrdUsersController.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-195

#196 RDCC-3768: Disabled fortify scan until further notice
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-196

#197 fix: RDCC-3773 patch log4j to the latest version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-197

#199 fix: patch log4j to the 2.16.0 in all applications to fix CVE-2021-45046
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-199

#198 fix: RDCC-3782 Upgraded versions suggested by bot
  .dependabot/config.yml
  .github/dependabot.yml
  build.gradle
  lombok.config
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-198

#212 Fix: Upgrading log4j to fix CVE-2021-45105
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-212
