Repository hmcts/rd-judicial-api, pull requests merged in 2022-06, with the labels that each got.

#307 feat: RDCC-4781 Added multi-architecture ACR Task template
  Dockerfile
  acb.tpl.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-307

#304 Feat:To handle 500 HTTP responses
  src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/SecurityEndpointFilter.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/advice/UnauthorizedException.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/repository/IdamRepository.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/controller/advice/UnauthorizedExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/repository/IdamRepositoryTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-304

#312 config: RDCC-4844 added git hub workflow to auto merge renovate PRs
  .github/workflows/combine-prs.yml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-312

#310 JRD Type ahead API Response change
  src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/RefreshUserProfileIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/SearchUsersIntegrationTest.java
  src/integrationTest/resources/db/testmigration/V1_33__delete_mrd_columns.sql
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/AppointmentRefreshResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/UserProfileRefreshResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/UserSearchResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/Appointment.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/domain/UserProfile.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/repository/RegionMappingRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/repository/ServiceCodeMappingRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
  src/main/resources/db/migration/V1_33__delete_mrd_columns.sql
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/TestSupport.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/domain/AppointmentTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/domain/UserProfileTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-310

#326 RDCC-4849: Collating DependaBot PRs
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-326

#337 Judicial - Update Region mapping table based on new OPT Codes
  src/integrationTest/resources/db/testmigration/V1_34__update_region_mapping.sql
  src/main/resources/db/migration/V1_34__update_region_mapping.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-337

#341 Rdcc 4880 jrd
  src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/RefreshUserProfileIntegrationTest.java
  src/integrationTest/resources/db/testmigration/V1_28__insert_user_profile_auth_appt.sql
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/util/RefDataConstants.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-341

#342 fix: RDCC-4948 Altered the mutation threshold
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-342

#343 Feat:RDCC-4959:Changes made to update ticket_code mapping
  src/integrationTest/resources/db/testmigration/V1_35__update_ticket_code_mapping.sql
  src/main/resources/db/migration/V1_35__update_ticket_code_mapping.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-343

#344 RDCC-5007: Adding Suppression for `CVE-2022-34305`
  charts/rd-judicial-api/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-344
