Repository hmcts/rd-judicial-api, pull requests merged in 2022-02, with the labels that each got.

#234 Upgrade Gradle 7.3.3
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-234

#235 Rdcc 3945 CVE fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-235

#233 RDCC-3946: CVE fixes
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-233

#228 RDCC-3923: JRD-api Remove Deprecated Jcenter Repository
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-228

#236 logged idam bearer token exception
  src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/RestAuthenticationEntryPoint.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/SecurityConfiguration.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-236

#239 fix: Bump base java helm chart to 3.7.1
  build.gradle
  charts/rd-judicial-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-239

#241 fix: RDCC-4088 Fix nightly build failure due to CWE-862: Missing Authorization
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-241

#242 Rdcc 4060 and RDCC-3979 scripts
  src/main/resources/db/migration/V1_29__insert_judicial_location_mapping.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-242

#244 Enhanced functional and integration test cases
  src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/JudicialUsersFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/judicialapi/client/JudicialApiClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/FetchUsersIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/RefreshUserProfileIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/SearchUsersIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/wiremock/WireMockExtension.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-244
