Repository hmcts/rd-judicial-api, pull requests merged in 2022-05, with the labels that each got.

#298 RDCC-4633: Upgrading `launchDarklySdk` to `5.8.1` (CVE-2022-25647 Fix)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-298

#296 Feat:Changes made to fix app-insights issue
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-296

#300 RDCC-4690: Suppressing CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-300

#301 CVE Fix for tomcat embed core n websocket
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-301

#299 JRD : Update the JRD Refresh API to make Service Code as an array
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/RefreshUserProfileIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/AuthorisationRefreshResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-299
