Repository hmcts/rd-judicial-api, pull requests merged in 2022-12, with the labels that each got.

#391 CVE-2021-37533 Issue Suppression : RDCC - 6007
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-391

#395 Feat:RDCC-6027:eLinks : Update the tables for Judicial Reference Data
  src/integrationTest/resources/db/testmigration/V1_48__elinks_alter_tables.sql
  src/main/resources/db/migration/V1_48__elinks_alter_tables.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-395

#389 eLinks : Create new dataload_schedular_job table for Judicial Reference Data : RDCC-5921
  src/integrationTest/resources/db/testmigration/V1_47__elinks_create_dataload_schedular_job.sql
  src/integrationTest/resources/db/testmigration/V1_49__elinks_alter_dataload_schedular_audit.sql
  src/main/resources/db/migration/V1_47__elinks_create_dataload_schedular_job.sql
  src/main/resources/db/migration/V1_49__elinks_alter_dataload_schedular_audit.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-389

#396 Feat:RDCC-6048:Altered tables for elinks people api
  src/integrationTest/resources/db/testmigration/V1_50__elinks_alter_tables.sql
  src/main/resources/db/migration/V1_50__elinks_alter_tables.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-396

#397 Elinks launchdarkly flag
  src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/LaunchDarklyConfiguration.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/FeatureToggleServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-397

#398 Feat:RDCC-6063:JRD API dev branch - elinks changes
  charts/rd-judicial-api/values.preview.template.yaml
  charts/rd-judicial-api/values.yaml
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/advice/ExceptionMapper.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/configuration/ElinksFeignInterceptorConfiguration.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksController.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/advice/ErrorResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/advice/ForbiddenException.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/BaseLocation.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/Location.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/exception/ElinksException.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/exception/JudicialDataLoadException.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/feign/ElinksFeignClient.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/BaseLocationRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/LocationRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/BaseLocationResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/ElinkBaseLocationResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/ElinkBaseLocationWrapperResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/ElinkLocationResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/ElinkLocationWrapperResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/LocationResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/ELinksService.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/util/JsonFeignResponseUtil.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksControllerTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/BaseLocationRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/LocationRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksBaseLocationServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-398

#399 Elinks idam search merge
  build.gradle
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/configuration/IdamTokenConfigProperties.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksController.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/ElinkDataSchedularAudit.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/feign/IdamFeignClient.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/DataloadSchedularAuditRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/IdamOpenIdTokenResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/IdamResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/IdamElasticSearchService.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/util/JsonFeignResponseUtil.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-399
