Repository hmcts/rd-judicial-api, pull requests merged in 2022-08, with the labels that each got.

#357 Address CVE-2021-28170
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-357

#358 Judicial - Update Ticket Code to Service Code mapping for Family Private Law & Adoption Service
  src/integrationTest/resources/db/testmigration/V1_38__update_judicial_service_code_mapping.sql
  src/main/resources/db/migration/V1_38__update_judicial_service_code_mapping.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-358

#359 RDCC-5261: Upgrading postgresql to version 42.4.1
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-359

#363 Add backstage configuration file
  catalog-info.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-363

#362 Refactor code to remove the hard coding
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-362
