Repository hmcts/rd-judicial-api, pull requests merged in 2023-04, with the labels that each got.

#543 Fix nightly build with audit.json change
  audit.json
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-543

#544 Fix nightly build with audit.json change
  audit.json
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-544

#541 [RDCC-6625]Update the SQL query to fetch only the required fields
  src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/SearchUsersIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/response/UserSearchResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/repository/UserProfileRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/TestSupport.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-541

#546 DTSRD-235 - update build.gradle for verifying pact and publish results
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-546

#549 alter table file added
  config/owasp/suppressions.xml
  src/integrationTest/resources/db/testmigration/V1_57__elinks_alter.sql
  src/main/resources/db/migration/V1_57__elinks_alter.sql
Labels: ns:rd, prd:rd, no-changes, rel:rd-judicial-api-pr-549

#552 cve for dev branch
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, no-changes, rel:rd-judicial-api-pr-552

#553 Addresses CVE-2023-20863
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-553

#554 [RDCC-6704]Added Flyway script as part of user story to sync all repo
  src/integrationTest/resources/db/testmigration/V1_56__elinks_shed_scheduler_table.sql
  src/main/resources/db/migration/V1_56__elinks_shed_scheduler_table.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-554

#550 eLinks : Data model changes to support eLinks V5.0 API specifications
  src/integrationTest/resources/db/testmigration/V1_57__elinks_alter.sql
  src/main/resources/db/migration/V1_57__elinks_alter.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-550

#556 eLinks : Data model changes to support eLinks V5.0 API specifications
  src/integrationTest/resources/db/testmigration/V1_58__elinks_alter.sql
  src/main/resources/db/migration/V1_58__elinks_alter.sql
Labels: ns:rd, prd:rd, no-changes, rel:rd-judicial-api-pr-556
