Repository hmcts/rd-judicial-api, pull requests merged in 2023-10, with the labels that each got.

#660 DTSRD-1256 Upgrade postgres to V15
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-judicial-api-pr-660

#663 DTSRD-1456
  build.gradle
  charts/rd-judicial-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-663

#656 Rdcc 7033
  build.gradle
  charts/rd-judicial-api/Chart.yaml
  charts/rd-judicial-api/values.preview.template.yaml
  charts/rd-judicial-api/values.yaml
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/BaseLocationsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/DeletedIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LeaversIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LocationsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
  src/integrationTest/resources/application-test.yml
  src/integrationTest/resources/db/testmigration/V1_86__elinks_responses_alter_tables.sql
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/ElinkDataExceptionRecords.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/ElinksResponses.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/ElinksResponsesRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobScheduler.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinkDataExceptionHelper.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksResponsesHelper.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1_84__elinks_responses_alter_tables.sql
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksBaseLocationServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksDeletedServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksLeaversServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksResponsesHelperTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-656, enable_keep_helm

#661 eLinks: Additional call to IDAM to fetch SIDAM Id
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/IdamElasticSearchIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LeaversIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksReferenceDataClient.java
  src/integrationTest/resources/application-test.yml
  src/integrationTest/resources/wiremock_responses/idamResponsefromObjectId.json
  src/integrationTest/resources/wiremock_responses/people.json
  src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/LaunchDarklyConfiguration.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksController.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/ProfileRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/response/ElinkIdamWrapperResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobScheduler.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/IdamElasticSearchService.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/FeatureToggleServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/ElinksControllerTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImplTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-judicial-api-pr-661

#666 DTSRD-1466. Remove branches to sync -judicial demo and master
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-666

#667 DTSRD-1466. Remove branches to sync -judicial demo
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-667

#652 eLinks : Changes in ingestion to accept new field
  src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderV2Test.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksAuthorisationsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationForExistingObjectId.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationForObjectId.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationForSidamIdisPresent.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationPartialTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksFailedApiPublishingStatusEndToEndIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksFailedForExtraBaseLocationIdEndToEndIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksLoadPeopleDataWithDuplicate.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
  src/integrationTest/resources/db/testmigration/V1_87__elinks_alter_judicial_additional_role.sql
  src/integrationTest/resources/wiremock_responses/people.json
  src/integrationTest/resources/wiremock_responses/people_del.json
  src/integrationTest/resources/wiremock_responses/people_duplicate.json
  src/integrationTest/resources/wiremock_responses/people_duplicateobject.json
  src/integrationTest/resources/wiremock_responses/people_null_appointmentId.json
  src/integrationTest/resources/wiremock_responses/people_part.json
  src/integrationTest/resources/wiremock_responses/people_test.json
  src/integrationTest/resources/wiremock_responses/testpeople_withoutsidam.json
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/request/RoleRequest.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/JudicialRoleType.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinkUserServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
  src/main/resources/db/migration/V1_85__elinks_alter_judicial_additional_role.sql
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImplTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-judicial-api-pr-652

#671 Addresses CVE-2023-42794, CVE-2023-42795 and CVE-2023-45648
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-671

#677 suppress CVE-2023-5590
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-677

#679 DTSRD-1456.suppressing as no known netty handler version available without vulnerability
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-679

#669 Rdcc 7099
  charts/rd-judicial-api/Chart.yaml
  charts/rd-judicial-api/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/AppointmentsRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/AuthorisationsRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/JudicialRoleTypeRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/ProfileRepository.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/scheduler/ElinksApiJobScheduler.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinkDataExceptionHelper.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ELinksServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinkDataExceptionHelperTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-judicial-api-pr-669
