Repository hmcts/rd-judicial-api, pull requests merged in 2023-06, with the labels that each got.

#576 DTSRD-554: fix CVE-2023-20883
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-576

#575 Mutation test coverage
  config/owasp/suppressions.xml
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-575

#574 Update README.md
  README.md
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-574

#579 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-579
