Repository hmcts/rd-judicial-api, pull requests merged in 2023-12, with the labels that each got.

#712 Addresses CVE-2023-34055, CVE-2023-46589
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-712

#721 eLinks : Region Mapping Update for eLinks Go-Live
  src/integrationTest/resources/db/testmigration/V1_94__elinks_jrd_lrd_region.sql
  src/main/resources/db/migration/V1_92__elinks_insert_jrd_lrd_region_mapping.sql
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-judicial-api-pr-721

#725 Rdcc 7223
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/RefDataElinksConstants.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/util/SendEmail.java
  src/main/resources/application.yaml
  src/main/resources/templates/simple-template-objectIdDuplicate.ftl
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/util/SendEmailTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-judicial-api-pr-725

#734 Update dependencycheck to use default version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-734

#730 elinks : location mapping table update
  src/integrationTest/resources/db/testmigration/V1_95__elinks_jrd_lrd_region.sql
  src/main/resources/db/migration/V1_93__elinks_insert_jrd_lrd_region_mapping.sql
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-judicial-api-pr-730
