Repository hmcts/rd-judicial-api, pull requests merged in 2023-05, with the labels that each got.

#532 Upgraded to gradle wrapper 7.4.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-532

#557 eLinks : Data model changes to support eLinks V5.0 API specifications
  config/owasp/suppressions.xml
  src/integrationTest/resources/db/testmigration/V1_58__elinks_alter.sql
  src/main/resources/db/migration/V1_58__elinks_alter.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-557

#558 addresses CVE-2023-20873, CVE-2023-20862
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-558

#555 [RDCC-6538]eLinks : Write End to end Integration test for Success/Failure
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/BaseLocationsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksFailedApiPublishingStatusEndToEndIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksFailedForExtraBaseLocationIdEndToEndIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/IdamElasticSearchIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LeaversIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/LocationsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/SchedulerElinksJobIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksEnabledIntegrationTest.java
  src/integrationTest/resources/wiremock_responses/base_location.json
  src/integrationTest/resources/wiremock_responses/extrabaselocation-id-for-failure-people.json
  src/integrationTest/resources/wiremock_responses/idamresponse.json
  src/integrationTest/resources/wiremock_responses/leavers.json
  src/integrationTest/resources/wiremock_responses/location.json
  src/integrationTest/resources/wiremock_responses/people.json
Labels: ns:rd, prd:rd, no-changes, rel:rd-judicial-api-pr-555

#559 Removing CVE suppression since fix is pushed to master
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-559

#564 JRD: Test Cases can be clubbed as Parameterised tests
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/RefreshUserProfileIntegrationTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/service/impl/JudicialUserServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-564

#566 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-566

#572 DTSRD-456: fix CVE-2023-28709
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-572

#568 DTSRD-435: Add Base_Location mapping for <service_code> 'BHA1'
  src/main/resources/db/migration/V1_59__elinks_insert_judicial_location_mapping_table.sql
  src/main/resources/db/migration/V1_60__insert_judicial_location_mapping_table.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-568
