Repository hmcts/rd-judicial-api, pull requests merged in 2023-03, with the labels that each got.

#498 RDCC-6434 removing column from table
  config/owasp/suppressions.xml
  src/integrationTest/resources/db/testmigration/V1_52__alter_judicial_appointment.sql
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/controller/request/AppointmentsRequest.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/domain/Appointment.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImpl.java
  src/main/resources/db/migration/V1_52__alter_judicial_appointment.sql
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/ElinksPeopleServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-498

#499 [RDCC-6234] Address CVEs in all Reference Data repositories - Judicial Reference Data
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-499

#502 [RDCC-6234] -Fix for CVE-2023-24998
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-502

#509 initial test for populate the value
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksEnabledIntegrationTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-509

#500 RDCC-6243 : Upgrade Libs in API projects
  build.gradle
  infrastructure/.terraform-version
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, no-changes, rel:rd-judicial-api-pr-500

#526 Addressing Sonar Issues
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/JrdUsersController.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/controller/WelcomeController.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/oidc/JwtGrantedAuthoritiesConverter.java
  src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/JudicialUserServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/controller/controller/advice/UnauthorizedExceptionTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-526

#528 RDCC-6609 - suppress CVE-2022-1471
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-528

#530 Nightly build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-530

#533 Nightly build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-533

#529 fix: Enhancement for unit and inetgration test cases
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinkClientsCommonIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/IdamElasticSearchIntegrationTest.java
  src/test/java/uk/gov/hmcts/reform/judicialapi/elinks/service/impl/IdamElasticSearchServiceImplTest.java
Labels: ns:rd, prd:rd, no-changes, rel:rd-judicial-api-pr-529
