Repository hmcts/rd-judicial-api, pull requests merged in 2024-02, with the labels that each got.

#746 DTSRD-2065.Adding force_user_permissions_trigger to get access to DTS JIT Access rd DB Reader SC
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, destroy, rel:rd-judicial-api-pr-746

#747 DTSAM-132: Enable 2 new authorisation for Magistrate access in Private Law
  src/integrationTest/resources/db/testmigration/V1_97__elinks_insert_service_code_mapping.sql
  src/main/resources/db/migration/V1_95__elinks_insert_service_code_mapping.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-747

#748 Addresses CVE-2023-34042
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-748

#749 DTSRD-2214:remove First Tier - Social Entitlement judges (ticket code 376) from the list.
  src/integrationTest/resources/db/testmigration/V1_98_delete_service_code_mapping.sql
  src/main/resources/db/migration/V1_96_delete_service_code_mapping.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-749

#750 DTSRD-2214: remove First Tier - Social Entitlement judges (ticket code 376) from the list.
  src/integrationTest/resources/db/testmigration/V1_98__delete_service_code_mapping.sql
  src/main/resources/db/migration/V1_96__delete_service_code_mapping.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-750

#751 DTSRD-2214: remove First Tier - Social Entitlement judges (ticket code 376) from the list.
  .gitignore
  src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/ProfileRepository.java
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-751
