Repository hmcts/rd-judicial-api, pull requests merged in 2024-10, with the labels that each got.

#909 Trigger pipeline build
  README.md
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-909

#910 DTSRD-3477 Fix local DependencyCheck, version upgraded to 10.0.3
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-910

#914 DTSRD-3538 Fix Demo Pipeline - dbmigrate:demo env.DB_READER_USERNAME …
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-914

#913 DTSRD-2029 eLinks : Post-Production - Flyway Config
  build.gradle
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-judicial-api-pr-913

#915 DTSRD-3538 Fix Branch Pipelines - Reader username added for ITHC and …
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-915

#917 DTSRD-3567 Elinks - Audit tables were not accessible in PROD
  src/main/resources/db/migration/V1_8__elinks_grant_access_dbjudicialdata_for_aduit_tables.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-917

#919 DTSRD-3560 Nightly Broken by Mutation Tests - PI Test excludedClasses…
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-919

#920 DTSRD-3562 Swagger Publishing
  .github/workflows/swagger.yml
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/docs/SwaggerPublisherTest.java
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-920

#922 DTSRD-3583 Mutation Tests BootClassPathSupported False Error
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-922

#921 DTSRD-3580 Jenkins Test Reports to Publish on Failure - afterSuccess(…
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-921

#923 DTSRD-3583 PI Test Version Config - pitestVersion added to pitest con…
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-923
