Repository hmcts/rd-judicial-api, pull requests merged in 2024-07, with the labels that each got.

#860 DTSRD-3041
  src/main/resources/testcontainers.properties
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-860

#854 DTSRF-2900: INC5616053 - Judge isn't showing on Judicial Lookup
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/terraform.tf
  infrastructure/variables.tf
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksJobSchedulerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/PeopleIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ElinksDataLoadBaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/ContainerImageNameSubstitutor.java
  src/integrationTest/resources/db/testmigration/V1_99__alter_judicial_office_authorisation.sql
  src/integrationTest/resources/testcontainers.properties
  src/integrationTest/resources/wiremock_responses/people_null_appointment_id_for_authorisation.json
  src/main/resources/db/migration/V1_97__alter_judicial_office_authorisation.sql
Labels: ns:rd, prd:rd, enable_keep_helm, aat/no-changes, prod/no-changes, rel:rd-judicial-api-pr-854

#862 Build fix: Update terraform version
  infrastructure/.terraform-version
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-judicial-api-pr-862

#883 Update build.gradle to Fix builds
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-883

#891 Update build.gradle. Fix Build
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-891

#900 Cleanup - delete testcontainers.properties
  src/main/resources/testcontainers.properties
Labels: ns:rd, prd:rd, rel:rd-judicial-api-pr-900
