Repository hmcts/rd-judicial-api, pull requests merged in 2025-01, with the labels that each got.

#949 CME-249: Database monitoring and alerting on RD repositories
  Jenkinsfile_CNP
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-judicial-api-pr-949

#950 CME-295: Update azurerm
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-judicial-api-pr-950

#959 DTSRD-4062
  build.gradle
Labels: ns:rd, prd:rd

#964 DTSRD-4065
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/contractTest/java/uk/gov/hmcts/reform/judicialapi/provider/JrdApiProviderV2Test.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksRefreshUserProfileIntegrationTestAudit.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/util/ELinksBaseIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/util/AuthorizationEnabledIntegrationTest.java
Labels: ns:rd, prd:rd
